# Generated by Django 4.2.16 on 2024-11-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ShoppingList',
        ),
    ]
