# Generated by Django 4.2.16 on 2024-11-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_list.shoppinglist'),
        ),
    ]
