# Generated by Django 4.2.16 on 2024-11-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0006_shoppinglist_quantity_alter_shoppinglist_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
